<?
include 'inc/datos_db.inc';
$link = mysql_connect($db_host, $db_user, $db_pass);
$cliente_id = $_GET["cliente_id"];

mysql_select_db($db_name_clientes, $link);

$query = sprintf("SELECT cliente_nombre,cliente_direccion,cliente_localidad,cliente_provincia,cliente_telefono,cliente_contacto,cliente_email,cliente_web,cliente_email_ventas1_on,cliente_email_ventas1,cliente_email_ventas1_idioma,cliente_email_ventas2_on,cliente_email_ventas2,cliente_email_ventas2_idioma,cliente_notificacion_gwoff,cliente_notificacion_utroff,cliente_notificacion_utcoff,cliente_notificacion_gwbat,cliente_notificacion_utrbat,cliente_notificacion_utrcob FROM clientes_datos WHERE cliente_id='%s'",$cliente_id);
$result = mysql_query($query,$link); 
if(!$result)
{
	echo "ERROR";
}
else
{	
	echo "<cliente>";
	if($row = mysql_fetch_array($result))
	{
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_nombre';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_nombre'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_direccion';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_direccion'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_localidad';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_localidad'];
		echo "</valor>";
		echo "</parametro>";			
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_provincia';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_provincia'];
		echo "</valor>";
		echo "</parametro>";	
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_telefono';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_telefono'];
		echo "</valor>";
		echo "</parametro>";	
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_contacto';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_contacto'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_email';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_email'];
		echo "</valor>";
		echo "</parametro>";	
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_web';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_web'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'email1_on';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_email_ventas1_on'];
		echo "</valor>";
		echo "</parametro>";	
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_email_comercial1';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_email_ventas1'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'email1_idioma';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_email_ventas1_idioma'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'email2_on';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_email_ventas2_on'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_email_comercial2';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_email_ventas2'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'email2_idioma';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_email_ventas2_idioma'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_notificacion_gwoff';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_notificacion_gwoff'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_notificacion_utroff';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_notificacion_utroff'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_notificacion_utcoff';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_notificacion_utcoff'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_notificacion_gwbat';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_notificacion_gwbat'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_notificacion_utrbat';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_notificacion_utrbat'];
		echo "</valor>";
		echo "</parametro>";
		echo "<parametro>";
		echo "<nombre>";
			echo 'cliente_notificacion_utrcob';
		echo "</nombre>";
		echo "<valor>";
			echo $row['cliente_notificacion_utrcob'];
		echo "</valor>";
		echo "</parametro>";
	}
	echo "</cliente>";
}

mysql_free_result($result);
mysql_close($link);
?>