<?session_start();
	include 'inc/idiomas.inc';
	include "inc/funciones_indice.inc";
	$nombre_actual=$_SESSION['usuario'];
	$perfil_actual=$_SESSION['perfil'];
	
	$menu = $_GET["menu"];

	if ($_SESSION['autentificado_rf2'] == 1)
	{
		switch ($menu)
		{
			// mapa
			case 1:
				echo '<table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-family:Arial, Helvetica, sans-serif; font-size:10px;">';
				echo '<tr>';
				echo '	<td style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#FFF; background-color:#999">';
				echo '		&nbsp;&nbsp;<strong>'.$idiomas[$_SESSION['opcion_idioma']]['title_gateways'].'</strong>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" valign="top">';
				echo '		<select id="comboGateways" onclick="OnChangeGateway()" onchange="OnChangeGateway()" size="18" style="width:100%;height:50px;margin:0px 0 5px 0;"/>';
		    	echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#FFF; background-color:#999">';
				echo '		&nbsp;&nbsp;<strong>'.$idiomas[$_SESSION['opcion_idioma']]['title_nodos'].'</strong>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" valign="top">';
				echo '		<select id="comboNodos" onclick="OnChangeNodo()" onchange="OnChangeNodo()" size="18" style="width:100%;height:200px;margin:0px 0 5px 0;"/>';
		    	echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#FFF; background-color:#999">';
				echo '		&nbsp;&nbsp;<strong>'.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</strong>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" valign="top">';
				echo '		<select id="comboUTCs" onclick="OnChangeUTC()" onchange="OnChangeUTC()" size="18" style="width:100%;height:200px;margin:0px 0 5px 0;"/>';
		    	echo '	</td>';
				echo '</tr>';
				echo '</table>';
				break;
				
			// datos
			case 2:
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text4'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_GW_Check" onclick="OnFilterGW()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general11'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr height="60%">';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_Nodo_Check" onclick="OnFilterNodo()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general12'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr height="60%">';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_UTC_Check" onclick="OnFilterUTC()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text7'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general20'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_GW" width="80px" class="RFNETtextINV" onchange="onFilterGWSelect(0)"></select>';				
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_GWSensor_Check" onclick="OnFilterGWSensor()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_GWSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';			
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general21'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_Nodo" width="80px" class="RFNETtextINV" onchange="onFilterNodeSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_NodeSensor_Check" onclick="OnFilterNodeSensor()" class="RFNETtextINV"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_NodeSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_UTC" width="80px" class="RFNETtextINV" onchange="onFilterUTCSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_UTCSensor_Check" onclick="OnFilterUTCSensor()" class="RFNETtextINV"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_UTCSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general31'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_Evento" width="80px" onchange="OnCambioEvento()" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Filtro_Fecha_Check" onclick="OnFilterFecha()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general8'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" class="datepicker" id="FechaInicial" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';
				break;
				
			// informes
			case 3:
				echo '<table border="0" width="100%">';
				echo '<tr><td><br/></td></tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general237'].':</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_Informe" width="80px" class="RFNETtextINV" onchange="onTipoInforme();vRellenar_Controles_Informes();"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left"  id="td_titulo_fecha">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general97'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_titulo_fecha_inicial">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				/*echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" readonly="true" id="FechaInicial" style="text-align:center;width:90px"  class="RFNETtextINV">&nbsp;<img id="Img_FechaInicial" name="ON_Init" src="js/img/cal.gif" width="20px" height="20px" border="0" valign="center" onclick="OnFechaInicialInformes()">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" readonly="true" style="text-align:center;width:90px" class="RFNETtextINV">&nbsp;<img id="Img_FechaFinal" name="ON_Fin" src="js/img/cal.gif" width="20px" height="20px" border="0" valign="center" onclick="OnFechaFinalInformes()">';
				echo '	</td>';
				echo '</tr>';*/
				echo '<tr>';
				echo '	<td align="left" id="td_fecha_inicial">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" class="datepicker" id="FechaInicial" style="text-align:center;width:140px">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_titulo_fecha_final">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_fecha_final">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_info_title">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text4'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_evento">';
				echo '		&nbsp;&nbsp;<select id="Filtro_combo_Evento" width="80px" onchange="OnCambioEventoInformes()" class="RFNETtextINV" onchange="onFilterNodeSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_filtrar_title">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text3'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_informe_dispositivo">';
				echo '		&nbsp;&nbsp;<select id="Filtro_combo_Dispositivo" width="80px" height="100px" class="RFNETtextINV" ></select>';				
				echo '	</td>';
				echo '</tr>';
				
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['plantilla1'].':</span>&nbsp;&nbsp;&nbsp;<input type="text" id="Input_Nombre_Plantilla" style="width:70px" class="RFNETtextINV"></input>';
				echo '	</td>';
				echo '</tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" value="'.$idiomas[$_SESSION['opcion_idioma']]['plantilla2'].'" id="bGuardaPlantilla" style="text-align:center;width:120px" class="boton_fino_medio" onclick="onGuardarPlantilla()"/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['plantilla3'].':';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="td_informe_dispositivo">';
				echo '		&nbsp;&nbsp;<select id="Plantillas_Lista" style="width:90%;height:60px" class="RFNETtextINV" multiple="multiple" onchange="OnChangePlantilla()"></select><input type="hidden" id="user_name" value="'.$_SESSION['usuario'].'"></input>';				
				echo '	</td>';
				echo '</tr>';
				echo '</tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" value="'.$idiomas[$_SESSION['opcion_idioma']]['plantilla7'].'" id="bEliminarPlantilla" style="text-align:center;width:120px" class="boton_fino_medio" onclick="onEliminarPlantilla()"/>';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';
				break;
				
			// config nodo
			case 4:
				if ($perfil_actual > 1)
				{
					echo "";
				}
				else
				{
					echo "";
				}
				break;
				
			// config nodo av
			case 5:
				if ($perfil_actual > 1)
				{
					echo "";
				}
				else
				{
					echo "";
				}
				break;
				
			// config gw
			case 6:
				if ($perfil_actual > 1)
				{
					echo "";
				}
				else
				{
					echo "";
				}
				break;
				
			// gestion
			case 7:
			case 10:
			case 11:
				echo '<table border="0" width="100%" cellpadding="0" cellspacing="0">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_vista" onclick="OnSubmenuVistaGeneral()">+ '.$idiomas[$_SESSION['opcion_idioma']]['general47'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_vista"></td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_general" onclick="OnSubmenuConfigGeneral(\''.$_SESSION["id_cliente"].'\')">+ '.$idiomas[$_SESSION['opcion_idioma']]['general75'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_general"></td>';
				echo '</tr>';				
				echo '<tr>';
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_et" onclick="OnSubmenuConfigET()">+ '.$idiomas[$_SESSION['opcion_idioma']]['general250'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_et"></td>';
				echo '</tr>';				
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_users" onclick="OnSubmenuUsuarios()">- '.$idiomas[$_SESSION['opcion_idioma']]['general59'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_Instalaciones" onclick="OnSubmenuInstalaciones()">+ '.$idiomas[$_SESSION['opcion_idioma']]['general10'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_inst"></td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_Dispositivos" onclick="OnSubmenuDispositivos()">+ '.$idiomas[$_SESSION['opcion_idioma']]['general9'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_disp"></td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_Notificaciones" onclick="OnSubmenuNotificaciones()">+ '.$idiomas[$_SESSION['opcion_idioma']]['general6'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_notifica"></td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_ColaEnvios" onclick="OnSubmenuColaEnvios()">- '.$idiomas[$_SESSION['opcion_idioma']]['general284'].'</a>';
				echo '	</td>';
				echo '</tr>';				
				echo '<tr>';
				echo '	<td align="left">';
				//echo '		<br/>';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';				
				echo '</table>';
				break;
				
			// soporte
			case 8:
				echo "";
				break;
				
			// ayuda
			case 9:
				echo "";
				break;

			// config gw low
			case 31:
				if ($perfil_actual > 1)
				{
					echo "";
				}
				else
				{
					echo "";
				}
				break;
				
			// config gw lowt
			case 36:
				if ($perfil_actual > 1)
				{
					echo "";
				}
				else
				{
					echo "";
				}
				break;
				
								
			case 50:
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_listuser" onclick="OnSubmenuListUsers()">- '.$idiomas[$_SESSION['opcion_idioma']]['general244'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="center" id="celda_submenu_listuser">';
				echo '		<select id="comboClientes" onchange="vActualizarUsuarios(this.options[this.selectedIndex].id)" size="16" style="width:80%;height:200px;margin:0px 0 5px 0;"/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_adduser" onclick="OnSubmenuAddUser()">- '.$idiomas[$_SESSION['opcion_idioma']]['general52'].' '.$idiomas[$_SESSION['opcion_idioma']]['general32'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_adduser"></td>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				break;
				
			case 52:
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_listinst" onclick="OnSubmenuListClientes()">- '.$idiomas[$_SESSION['opcion_idioma']]['general243'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="center" id="celda_submenu_listClientes">';
				echo '		<select id="comboClientes" onchange="vActualizarClientes(this.options[this.selectedIndex].id)" size="16" style="width:80%;height:200px;margin:0px 0 5px 0;"/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_addClientes" onclick="OnSubmenuAddCliente()">- '.$idiomas[$_SESSION['opcion_idioma']]['general52'].' '.$idiomas[$_SESSION['opcion_idioma']]['general1'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenu_addCliente"></td>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				break;
				
			// gestión admin
			case 53:
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_general" onclick="OnSubmenuAdminConfigGeneral()">- '.$idiomas[$_SESSION['opcion_idioma']]['general75'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_notificaciones" onclick="OnSubmenuAdminConfigNotificaciones('.iObtenerModoOffline().')">+ '.$idiomas[$_SESSION['opcion_idioma']]['general6'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenuadmin_notificaciones"></td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<a href="#" class="TextoMenuINV" id="submenu_consumo" onclick="OnSubmenuAdminConsumo('.iObtenerModoOffline().')">+ '.$idiomas[$_SESSION['opcion_idioma']]['general2'].'</a>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left" id="celda_submenuadmin_consumo"></td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';
				break;
				
			// notificaciones
			case 69:
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '  	<span class="TextoMenuINVNH">'.$idiomas[$_SESSION['opcion_idioma']]['general31'].':</span>';
				echo '		<select id="selEvento" onchange="OnSelectEventos(this.selectedIndex, 0)">';
				echo '			<option id="Alarmas">'.$idiomas[$_SESSION['opcion_idioma']]['general322'].'</option>';
				echo '			<option id="Historico">'.$idiomas[$_SESSION['opcion_idioma']]['general323'].'</option>';
				echo '			<option id="Notificaciones" selected>'.$idiomas[$_SESSION['opcion_idioma']]['general6'].'</option>';
				echo '			<option id="Diario">'.$idiomas[$_SESSION['opcion_idioma']]['general301'].'</option>';
				echo '		</select>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';				
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="TextoMenuINVNH">'.$idiomas[$_SESSION['opcion_idioma']]['report_text7'].':</span>';
				echo '	</td>';
				echo '</tr>';
				/*echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';*/
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="TextoMenuINVNH">- '.$idiomas[$_SESSION['opcion_idioma']]['general20'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_GW" width="80px" class="RFNETtextINV"></select>';				
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="TextoMenuINVNH">- '.$idiomas[$_SESSION['opcion_idioma']]['general21'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_Nodo" width="80px" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="TextoMenuINVNH">- '.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_UTC" width="80px" class="RFNETtextINV" onchange="onFilterUTCSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="TextoMenuINVNH">- '.$idiomas[$_SESSION['opcion_idioma']]['general31'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_Evento" width="80px" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="TextoMenuINVNH">- '.$idiomas[$_SESSION['opcion_idioma']]['general8'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaInicial" class="datepicker" style="text-align:center;width:140px">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';				
				echo '<tr>';
				echo '	<td align="center">';
				echo '		&nbsp;&nbsp;<input type="button" onclick="top.document.getElementById(\'iframe_mapa\').contentWindow.vActualizarConsumo()" value="'.$idiomas[$_SESSION['opcion_idioma']]['general51'].'" name="actualiza_consumo" id="actualiza_consumo" style="width:120px;text-align:center" class="boton_fino_largo"/>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';
				break;
			case 71:	
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '  	<span class="TextoMenuINV">'.$idiomas[$_SESSION['opcion_idioma']]['general31'].':</span>';
				echo '		<select id="selEvento" onchange="OnSelectEventos(this.selectedIndex, 0)">';
				echo '			<option id="Alarmas">'.$idiomas[$_SESSION['opcion_idioma']]['general322'].'</option>';
				echo '			<option id="Historico">'.$idiomas[$_SESSION['opcion_idioma']]['general323'].'</option>';
				echo '			<option id="Notificaciones">'.$idiomas[$_SESSION['opcion_idioma']]['general6'].'</option>';
				echo '			<option id="Diario" selected>'.$idiomas[$_SESSION['opcion_idioma']]['general301'].'</option>';
				echo '		</select>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';				
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaInicial" class="datepicker" style="text-align:center;width:140px">&nbsp;';
				//echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" readonly="true" id="FechaInicial" style="text-align:center;width:90px"  class="RFNETtextINV" ondblclick="top.document.getElementById(\'iframe_mapa\').contentWindow.vBorrar_Fecha(0)">&nbsp;<img id="Img_FechaInicial" name="ON_Init" src="js/img/cal.gif" width="20px" height="20px" border="0" valign="center" onclick="OnFechaInicial()">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px">&nbsp;';
				//echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" readonly="true" style="text-align:center;width:90px" class="RFNETtextINV" ondblclick="top.document.getElementById(\'iframe_mapa\').contentWindow.vBorrar_Fecha(1)">&nbsp;<img id="Img_FechaFinal" name="ON_Fin" src="js/img/cal.gif" width="20px" height="20px" border="0" valign="center" onclick="OnFechaFinal()">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';	
				echo '<td align="center" style="width:35%">';
				echo '	<input type="button" value="'.$idiomas[$_SESSION['opcion_idioma']]['general51'].'" id="Boton_Actualizar" onclick="parent.document.getElementById(\'iframe_mapa\').contentWindow.vActualizarTodo()" style="text-align:center;width:90px" class="boton_fino"/>';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';				
				break;			
				// procesado
			case 83:
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '  	<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['main_boton_procesado'].':</span>';
				echo '		<select onchange="OnBotonET()">';
				echo '			<option id="ETC" selected>'.$idiomas[$_SESSION['opcion_idioma']]['general312'].'</option>';
				echo '			<option id="ET0">'.$idiomas[$_SESSION['opcion_idioma']]['general313'].'</option>';
				echo '		</select>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';				
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text7'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general20'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_GW" width="80px" class="RFNETtextINV" onchange="onFilterGWSelect(0)"></select>';				
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Filtro_Fecha_Check" onclick="OnFilterFecha()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general8'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" class="datepicker" id="FechaInicial" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="center">';
				echo '		<input type="button" value="'.$idiomas[$_SESSION['opcion_idioma']]['general219'].' CSV" id="bDescargarCSV" style="text-align:center;width:120px" class="boton_fino_medio" onclick="onDescargarCSV()"/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="center">';
				echo '		<input type="button" value="'.$idiomas[$_SESSION['opcion_idioma']]['general219'].' PDF" id="bDescargarPDF" style="text-align:center;width:120px" class="boton_fino_medio" onclick="onDescargarPDF()"/>';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';
				break;
			case 84:
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '  	<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['main_boton_procesado'].':</span>';
				echo '		<select onchange="OnBotonProcesado()">';
				echo '			<option id="ETC">'.$idiomas[$_SESSION['opcion_idioma']]['general312'].'</option>';
				echo '			<option id="ET0" selected>'.$idiomas[$_SESSION['opcion_idioma']]['general313'].'</option>';
				echo '		</select>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';				
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text7'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general20'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_GW" width="80px" class="RFNETtextINV" onchange="onFilterGWSelect(0)"></select>';				
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Filtro_Fecha_Check" onclick="OnFilterFecha()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general8'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" class="datepicker" id="FechaInicial" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';
				break;	

			case 89:	
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '  	<span class="TextoMenuINV">'.$idiomas[$_SESSION['opcion_idioma']]['general31'].':</span>';
				echo '		<select id="selEvento" onchange="OnSelectEventos(this.selectedIndex, 0)">';
				echo '			<option id="Alarmas" selected>'.$idiomas[$_SESSION['opcion_idioma']]['general322'].'</option>';
				echo '			<option id="Historico">'.$idiomas[$_SESSION['opcion_idioma']]['general323'].'</option>';
				echo '			<option id="Notificaciones">'.$idiomas[$_SESSION['opcion_idioma']]['general6'].'</option>';
				echo '			<option id="Diario">'.$idiomas[$_SESSION['opcion_idioma']]['general301'].'</option>';
				echo '		</select>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text4'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_GW_Check" onclick="OnFilterGW()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general11'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr height="60%">';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_Nodo_Check" onclick="OnFilterNodo()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general12'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr height="60%">';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_UTC_Check" onclick="OnFilterUTC()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text7'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general20'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_GW" width="80px" class="RFNETtextINV" onchange="onFilterGWSelect(0)"></select>';				
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_GWSensor_Check" onclick="OnFilterGWSensor()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_GWSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';			
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general21'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_Nodo" width="80px" class="RFNETtextINV" onchange="onFilterNodeSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_NodeSensor_Check" onclick="OnFilterNodeSensor()" class="RFNETtextINV"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_NodeSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_UTC" width="80px" class="RFNETtextINV" onchange="onFilterUTCSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_UTCSensor_Check" onclick="OnFilterUTCSensor()" class="RFNETtextINV"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_UTCSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Filtro_Fecha_Check" onclick="OnFilterFecha()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general8'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" class="datepicker" id="FechaInicial" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';				
				break;	
			case 90:	
				echo '<table border="0" width="100%">';
				echo '<tr>';
				echo '	<td align="left">';
				echo '  	<span class="TextoMenuINV">'.$idiomas[$_SESSION['opcion_idioma']]['general31'].':</span>';
				echo '		<select id="selEvento" onchange="OnSelectEventos(this.selectedIndex, 0)">';
				echo '			<option id="Alarmas">'.$idiomas[$_SESSION['opcion_idioma']]['general322'].'</option>';
				echo '			<option id="Historico" selected>'.$idiomas[$_SESSION['opcion_idioma']]['general323'].'</option>';
				echo '			<option id="Notificaciones">'.$idiomas[$_SESSION['opcion_idioma']]['general6'].'</option>';
				echo '			<option id="Diario">'.$idiomas[$_SESSION['opcion_idioma']]['general301'].'</option>';
				echo '		</select>';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text4'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_GW_Check" onclick="OnFilterGW()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general11'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr height="60%">';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_Nodo_Check" onclick="OnFilterNodo()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general12'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr height="60%">';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Ver_UTC_Check" onclick="OnFilterUTC()" checked="true"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['report_text7'].':</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general20'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_GW" width="80px" class="RFNETtextINV" onchange="onFilterGWSelect(0)"></select>';				
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_GWSensor_Check" onclick="OnFilterGWSensor()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_GWSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';			
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general21'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_Nodo" width="80px" class="RFNETtextINV" onchange="onFilterNodeSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_NodeSensor_Check" onclick="OnFilterNodeSensor()" class="RFNETtextINV"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_NodeSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<br/>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['general254'].'</span>&nbsp;&nbsp;&nbsp;<select id="Filtro_combo_UTC" width="80px" class="RFNETtextINV" onchange="onFilterUTCSelect(0)"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="Filtro_UTCSensor_Check" onclick="OnFilterUTCSensor()" class="RFNETtextINV"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general102'].'</span>&nbsp;&nbsp;<select id="Filtro_combo_UTCSensor" width="80px" disabled="true" class="RFNETtextINV"></select>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '<img width="166" height="5" src="images/menu2_separator.png">';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		<input type="checkbox" id="Filtro_Fecha_Check" onclick="OnFilterFecha()"/>&nbsp;&nbsp;<span class="RFNETtextINV">'.$idiomas[$_SESSION['opcion_idioma']]['general8'].'</span>';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text8'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" class="datepicker" id="FechaInicial" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;<span class="RFNETtextINV">- '.$idiomas[$_SESSION['opcion_idioma']]['report_text9'].'</span>&nbsp;&nbsp;&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '<tr>';
				echo '	<td align="left">';
				echo '		&nbsp;&nbsp;&nbsp;&nbsp;<input valign="top" align="center" type="text" id="FechaFinal" class="datepicker" style="text-align:center;width:140px" disabled="disabled">&nbsp;';
				echo '	</td>';
				echo '</tr>';
				echo '</table>';				
				break;		
			default:
				break;
		}
	}
	else
	{
		echo "";
	}
?>