<?php
/*
$email_source = "alertasconsum@gmail.com";
$smtp_servidor = "smtp.gmail.com";
$smtp_port = 587;
$smtp_user = "alertasconsum";
$smtp_pw = "chillida";
$TLS = 1;
*/

$email_source = "notificaciones@balmart.es";
$smtp_servidor = "mail.balmart.es";
$smtp_port = 25;
$smtp_user = "notificaciones_balm";
$smtp_pw = "amarrosa";
$TLS = 0;

//$email_target = 'soporte@balmart.es';
//$email_target = 'carmelo.garcia@balmart.es';
$email_target = 'sat@balmart.es';
$header_email = '<html><header><meta charset="ISO-8859-1"/></header><body>';
$footer_email = '</body></html>';
?>
