<?php
//$key_google_maps = 'ABQIAAAAeN3zlsKM03WacTGg21veRxQGB5fTUHzgVJs9tCmNUhDcr4en2RSjzBXjp3mWX9GT5bfoxc82h7xA1w';
//$key_google_maps = 'ABQIAAAAeN3zlsKM03WacTGg21veRxSfJa8EGOFl5AXPQAJ0fxIu0vbGhxSdPr3c-o3j5LVMIfefo-aOiLhFag';
//La siguiente es la buena de ONO
//$key_google_maps= 'ABQIAAAABNj8li5DUxNhXf9_v5GoHRRl3XeomRQ1e4iMUnRDmW60h32qSBSbF4m_zl1HLA5_00Su4b1kkmDRTQ';
//$key_google_maps = 'ABQIAAAAeN3zlsKM03WacTGg21veRxTSb06NlV119kZcsnPLKcoHd7GKihSL3IYRCUdD7dmEX0kuiNAY2ONMSw';
//Esta Key es la del servidor de Pruebas
//$key_google_maps='ABQIAAAABNj8li5DUxNhXf9_v5GoHRRbdt6AOcAH-1_ZBTBLYzM6JTJsGRTtnFI9qBPSyuWadVb1aKkwTg71Ew';
//Esta vale para todos los servers
$key_google_maps='AIzaSyD_ZI4Uvzk4ljUgwmqq7vpLsH14iaAqTww'; 
$version_google_maps = 3;
$GoogleClientId='gme-balmartsistemaselectronicos';
?>